### PR TITLE
Update settingtypes.txt & Use 0.4.16 API on Newer Servers

### PR DESCRIPTION
**Pull request by AntumDeluge**
Not sure if I used the best method for determining the Minetest server version. You may want to look at it closely.

### CODE REVIEW

**Comment by taikedz** [comment]
Looks fine to me - what are you concerns about "best method" of getting server version? So long as this works in 0.4.13 (Ubuntu 16.04's version , possibly still deployed in some places), I'm happy ...

**Comment by AntumDeluge** [comment]
Just wasn't sure if there was a better way.

Previously when I was submitting pull requests, I would simply change the methods to the newer API versions. then someone suggested a method to me about checking the Minetest version, but I don't remember it & can't find the thread/post. So I just came up with the method here. I'm not the best coder/scripter, so it wouldn't surprise me if someone else had a more efficient suggestion.

**Comment by taikedz** [comment]
There was an animated discussion about version number checking and use for feature checking in https://github.com/minetest/minetest/issues/4822. The preferred method apparently is to check for function existence, something like

```lua
if minetest.setting_get then
        minetest.log("setting_get")

elseif minetest.settings and minetest.settings.get then
        minetest.log("settings:get")

else
        minetest.log("nothing")
end
```

The conclusion of the discussion was that the main devs apparently didn't want version number to be a guarantor of a feature, which I guess makes sense in a case where an implementation is rolled back in later releases, or the server you're running in is a fork that changed the behaviour of what you were checking for.

Probably best if you could adjust your PR to conform to this practice...

**Comment by AntumDeluge** [comment]
Yes! That sounds familiar.

I have updated the pull request.
- Creates a `settings` object.
  - Set to `minetest.settings` if available.
  - Otherwise creates `settings:get` & `settings:get_bool` functions that call deprecated `minetest.setting_get` & `minetest.setting_getbool` respectively.

**Edit:** That's what I love about Lua, being able to check variables/objects event if they haven't been previously declared. 😃

**Comment by taikedz** [comment]
> I'm not the best coder/scripter

It looks efficient and clean to me :-)

**Comment by AntumDeluge** [comment]
Thank you for the compliment @taikedz. 😃

**Pull request merged**
